version: "3.9"
services:
  server:
    build: .
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LLM_MODEL=${LLM_MODEL:-gpt-4o-mini}
      - PG_URL=${PG_URL}
      - PORT=${PORT:-7679}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - CARDS_TTL_SECONDS=${CARDS_TTL_SECONDS:-900}
      - STATEMENT_TIMEOUT_MS=${STATEMENT_TIMEOUT_MS:-3000}
      - MAX_LIMIT=${MAX_LIMIT:-1000}
      - MOCK_LLM=${MOCK_LLM:-0}
      - MAX_RESPONSE_BYTES=${MAX_RESPONSE_BYTES:-5242880}
    ports:
      - "${PORT:-7679}:7679"
